"""LLM self-improvement relevance rule.

A paper is accepted when its title and abstract contain at least one language
model signal and at least one self-improvement signal. Both are OR-groups, so
the rule cannot be expressed with ``include_any`` and ``include_all`` alone.
"""

import re

from papers_pipeline.models import Paper
from papers_pipeline.topics import TopicDecision

SELF_IMPROVEMENT_PHRASES = (
    "self-improv",
    "self improv",
    "self-refine",
    "self-refinement",
    "self-correct",
    "self-play",
    "self-reward",
    "self-training",
    "self-train",
    "self-evolv",
    "self-evolution",
    "self-reflect",
    "self-critique",
    "self-critic",
    "self-instruct",
    "self-taught",
    "self-generated",
    "self-verif",
    "self-feedback",
    "self-alignment",
    "self-distillation",
    "self-bootstrap",
    "learn from its own",
    "learns from its own",
    "on its own outputs",
    "own generated data",
    "without human supervision",
    "without human annotation",
    "iterative refinement",
    "synthetic data generated by the model",
)

LANGUAGE_MODEL_PHRASES = (
    "language model",
    "large language",
    "reasoning model",
    "foundation model",
    "instruction tuning",
    "instruction-tuned",
    "chain-of-thought",
    "chain of thought",
    "rlhf",
    "gpt",
    "llama",
    "qwen",
    "mistral",
    "gemini",
    "claude",
    "deepseek",
    "vision-language",
    "multimodal model",
    # Self-evolving agents are almost always LLM agents, even when unstated.
    "agent",
)

# Bare "LLM"/"LM"/"VLM" need word boundaries: "llms" should match, "film" should not.
LANGUAGE_MODEL_ACRONYM = re.compile(r"\b(?:v?llms?|lms?|slms?|mllms?|vlms?)\b")


def accept_topic(paper: Paper) -> TopicDecision:
    """Accept papers about language models that improve from their own signal.

    Args:
        paper: Normalized paper to classify.

    Returns:
        Acceptance decision with the rule that decided it.
    """
    text = f"{paper.title} {paper.abstract}".lower()
    if not (
        any(phrase in text for phrase in LANGUAGE_MODEL_PHRASES)
        or LANGUAGE_MODEL_ACRONYM.search(text)
    ):
        return TopicDecision(False, "missing language model signal")
    if not any(phrase in text for phrase in SELF_IMPROVEMENT_PHRASES):
        return TopicDecision(False, "missing self-improvement signal")
    return TopicDecision(True, "accepted")
